import Head from "./head";
import Header from "./header";
import Footer from "./footer";
import "./globals.css";
// export const metadata: Metadata = {
//   title: "Harald's Blog",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head />
      <body>
        <div className="mx-auto max-w-2xl px-6">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
