import type { Metadata } from "next";

import Head from "./head";
import Header from "./header";
import Footer from "./footer";

// export const metadata: Metadata = {
//   title: "Harald's Blog",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head />
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
